## Numpy Library Exercises

In [1]:
import numpy as np

**1.** Given a random array, change the sign of elements whose values ​​are between 3 and 8

In [2]:
# your code
arr = np.random.randint(1,10,size=(1,10))
new_arr= (arr>=3) & (arr<=8)
res=arr[new_arr]
print(res)

[5 7 8 6 6 3 7 5]


**2.** Replace the maximum element of a random array with 0

In [3]:
# your code
arr = np.random.randint(1,10,size=(1,10))
arr[arr==arr.max()]=0
print(arr)

[[0 5 4 1 0 2 5 1 4 6]]


**3.** Construct the direct product of arrays (all combinations with each element). A two-dimensional array is provided as input.

In [9]:
# your code
a = np.array([1, 2])
b = np.array([4, 6])
res=np.array(np.meshgrid(a,b)).T.reshape(-1,2)
print(res)

[[1 4]
 [1 6]
 [2 4]
 [2 6]]


**4.** Given two arrays, A (8x3) and B (2x2), find rows in A that contain elements from each row in B, regardless of the order of the elements in B.

In [13]:
# your code
A = np.array([
    [1, 2, 3],
    [4, 6, 1],
    [2, 1, 5],
    [6, 4, 7],
    [8, 9, 0],
    [1, 4, 6],
    [3, 2, 1],
    [7, 8, 9]
])

B = np.array([
    [1, 2],
    [4, 6]
])
# mask1=np.isin(A,B[0]).sum(axis=1)==2
# mask2=np.isin(A,B[1]).sum(axis=1)==2;
# res=A[mask1|mask2]
# print(res)
result=[]
for row_a in A:
  for row_b in B:
    if np.isin(row_b,row_a).all():
      result.append(row_a)
      break
result=np.array(result)
print(result)

[[1 2 3]
 [4 6 1]
 [2 1 5]
 [6 4 7]
 [1 4 6]
 [3 2 1]]


**5.** Given a 10x3 matrix, find rows of unequal values ​​(for example, the row [2,2,3] remains, the row [3,3,3] is deleted)

In [22]:
# your code
A = np.array([
    [2, 2, 3],
    [3, 3, 3],
    [1, 4, 1],
    [5, 5, 5],
    [7, 8, 9],
    [6, 6, 2],
    [4, 4, 4],
    [9, 1, 9],
    [8, 8, 8],
    [1, 2, 3]
])

new=[]
for i in A:
   if not (i[0] == i[1] == i[2]):
        new.append(i)
result=np.array(new)
print(result)

[[2 2 3]
 [1 4 1]
 [7 8 9]
 [6 6 2]
 [9 1 9]
 [1 2 3]]


**6.** Given a two-dimensional array, remove the rows that are repeated.

In [28]:
# your code
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6],
    [2, 2, 2]
])
result = np.unique(A,axis=0)
print(result)

[[1 2 3]
 [2 2 2]
 [4 5 6]
 [7 8 9]]


______
______

For each of the following problems (1-5) you need to provide 2 implementations – one without using numpy (Consider that where the input or output should be a numpy array, there will simply be lists), and the second one is fully vectorized using numpy (without using Python loops/map/list comprehension).


__Note 1.__ It can be assumed that all specified objects are non-empty (for example, in __task 1__ there are non-zero elements on the diagonal of the matrix).

__Note 2.__ For most tasks, the solution takes no more than 1-2 lines.

___

* __Task 1__: Calculate the product of nonzero elements on the diagonal of a rectangular matrix.  
 For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) answer is 3.

In [32]:
# your code
X = np.array([[1, 0, 1],
              [2, 0, 2],
              [3, 0, 3],
              [4, 4, 4]
            ])

result = 1

for i in range(min(len(X), len(X[0]))):
    if X[i][i] != 0:
      result*=X[i][i]
print(result)

d = np.diag(X)
result = d[d != 0].prod()
print(result)

3
3


* __Task 2__: Two vectors x and y are given. Check if they define the same multiset.  
  For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) answer is True.

In [43]:
# your code
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

res = sorted(x) == sorted(y)
print(res)

result = np.array_equal(np.sort(x),np.sort(y))
print(result)

True
True


* __Task 3__: Find the maximum element in the vector x among the elements preceded by zero.
 For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) answer is 5.

In [62]:
# your code
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

res = []
for i in range(1,len(x)):
    if x[i - 1] == 0:
      res.append(x[i])
print(max(res))

result = x[1:][x[:-1]==0].max()
print(result)

5
5


* __Task 4__: Implement run-length encoding. For some vector x, it is necessary to return a tuple of two vectors of the same length. The first one contains numbers and the second one contains how many times they need to be repeated.  
 For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
# your code

* __Task 5__: Two samples of objects are given - X and Y. Calculate the matrix of Euclidean distances between objects. Compare with function scipy.spatial.distance.cdist by operating speed.

In [ ]:
# your code
X = [
    [1, 2],
    [3, 4],
    [5, 6]
]

Y = [
    [1, 1],
    [2, 2]
]

_______
________

* #### __Task 6__: CrunchieMunchies __*__

You work in the marketing department of a food company called MyCrunch, which is developing a new type of delicious, healthy cereal called **CrunchieMunchies**.

You want to show consumers how healthy your cereal is compared to other leading brands, so you've compiled nutrition data from several different competitors.

Your task is to use Numpy calculations to analyze this data and prove that your **СrunchieMunchies** - the healthiest choice for consumers.


In [63]:
import numpy as np

1. View the cereal.csv file. This file contains calorie counts for various brands of cereal. Download the data from the file and save it as calorie_stats.

In [66]:
calorie_stats = np.loadtxt("/data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

Store the answer in the variable average_calories and print the variable in the terminal

In [69]:
# your code
average_calories = np.mean(calorie_stats) - 60
print(round(average_calories,2))

46.88


3. Does the average calorie count accurately reflect the distribution of the data set? Let's sort the data and see.

Sort the data and store the result in the calorie_stats_sorted variable. Print the sorted information.

In [78]:
# your code
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)
mean = np.mean(calorie_stats_sorted)
print(mean)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]
106.88311688311688


4. It looks like most values ​​are above the mean. Let's see if the median is the most accurate measure of the data set.

Calculate the median of the data set and save your answer in median_calories. Print the median so you can see how it compares to the mean.

In [81]:
# your code
median_calories = np.median(calorie_stats)
print(median_calories)
print("Compare median to mean:",median_calories-mean)

110.0
Compare median to mean: 3.116883116883116


5. While the median shows that at least half of our values ​​are over 100 calories, it would be more impressive to show that a significant portion of the competitors have higher calorie counts than CrunchieMunchies.

Calculate various percentiles and print them until you find the lowest percentile that exceeds 60 calories. Store this value in the nth_percentile variable.

In [88]:
# your code
for i in range(101):
  percentile_value = np.percentile(calorie_stats,i)
  print(i,percentile_value)

  if percentile_value > 60:
    nth_percentile = i
    break
print("Percentile:",nth_percentile)

0 50.0
1 50.0
2 50.0
3 55.599999999999994
4 70.0
Percentile: 4


6. While the percentile shows us that most competitors have much higher calorie counts, it's an awkward concept to use in marketing materials.

Instead, let's calculate the percentage of cereals that contain more than 60 calories per serving. Save your answer in the more_calories variable and print it.

In [89]:
# your code
more_calories = np.mean(calorie_stats>60)*100
print(more_calories)

96.1038961038961


7. This is a really high percentage. This will be very useful as we promote CrunchieMunchies. But one question is: how big are the differences in the dataset? Can we generalize that most cereals contain around 100 calories or is the range even wider?

Calculate the magnitude of the deviation by finding the standard deviation. Save your answer in calorie_std and print it on the terminal. How can we incorporate this value into our analysis?

In [90]:
# your code
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Please write a short paragraph outlining your findings and how you believe this data can be used to Mycrunch's advantage in marketing CrunchieMunchies.

In [ ]:
# your code
The data shows that CrunchieMunchies has a strong advantage
compared to competing cereals.
While CrunchieMunchies contains only 60 calories per serving,
the average competitor cereal contains about 107 calories,
with a median of 110 calories. In addition, about 96% of
competitor cereals have more than 60 calories per serving.
Even though there is some variation in the data,
with a standard deviation of about 19 calories,
most competitors still have much higher calorie counts.
Mycrunch can use this information in marketing to promote CrunchieMunchies as
a lower-calorie cereal option for customers who want a lighter breakfast choice.
